// =====================================================================
// StockRidge — IDS, HASHING, TIME
// =====================================================================
// Runs unchanged on Node 20 and Cloudflare Workers. Both expose
// crypto.getRandomValues, crypto.subtle and crypto.randomUUID via the
// WebCrypto global, so nothing here touches node:crypto — that is the
// whole point of the decoupling.
//
// IDs: PharmaRidge used `lower(hex(randomblob(16)))` as a SQL DEFAULT.
// That is elegant but it means the ID is generated by the database, so an
// offline PWA cannot know the ID of the row it just created locally — and
// offline-first is the product. StockRidge therefore generates every ID
// in the application layer, BEFORE insert, so a queued offline sale
// already carries the identity it will have on the server. That is what
// makes the sync protocol idempotent by construction rather than by
// bookkeeping.
// =====================================================================

const cryptoGlobal = (typeof globalThis !== 'undefined' && globalThis.crypto) ? globalThis.crypto : null;

// 32 lowercase hex chars — same shape and same 128 bits of entropy as
// randomblob(16), so a migrated PharmaRidge database and a new StockRidge
// database are indistinguishable at the row level.
function newId() {
  if (cryptoGlobal && cryptoGlobal.getRandomValues) {
    const b = new Uint8Array(16);
    cryptoGlobal.getRandomValues(b);
    let s = '';
    for (let i = 0; i < b.length; i += 1) s += b[i].toString(16).padStart(2, '0');
    return s;
  }
  // Should never happen on either supported runtime; fail loudly rather
  // than emit a predictable ID, because a predictable ID on a
// hash-chained audit register is a tamper-evidence break.
  throw new Error('No cryptographic random source available');
}

// Human-facing reference numbers: receipts, POs, invoices, plan numbers.
// Deliberately NOT the row id — customers read "SR-LAG-2026-000431" on a
// receipt and quote it over the phone; a 32-hex id is unusable for that.
function refNumber(prefix, sequence, { width = 6 } = {}) {
  const n = Number(sequence) || 0;
  return `${prefix}-${String(n).padStart(width, '0')}`;
}

function toHex(buffer) {
  const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer);
  let s = '';
  for (let i = 0; i < bytes.length; i += 1) s += bytes[i].toString(16).padStart(2, '0');
  return s;
}

function utf8(str) {
  return new TextEncoder().encode(String(str == null ? '' : str));
}

// SHA-256 hex. Used for (a) the tamper-evident chain on the compliance /
// audit registers and (b) hashing request bodies for idempotency keys.
async function sha256Hex(input) {
  const subtle = cryptoGlobal && cryptoGlobal.subtle;
  if (!subtle) throw new Error('crypto.subtle unavailable');
  const digest = await subtle.digest('SHA-256', utf8(input));
  return toHex(digest);
}

// ---------------------------------------------------------------------
// PIN HASHING
// ---------------------------------------------------------------------
// StockRidge authenticates with short numeric PINs (minimum 4 digits),
// exactly like PharmaRidge, because that is what a shop counter with a
// shared till and 12 staff per shift can actually use. A 4-digit PIN has
// a 10,000-value keyspace, so the hash must be slow AND every account
// must carry its own salt; otherwise one leaked database yields every
// PIN in seconds. PBKDF2-SHA256 at 150k iterations is the WebCrypto
// primitive available on BOTH runtimes (bcrypt/scrypt/argon2 are not in
// crypto.subtle). The iteration count is stored with the hash so it can be
// raised later without invalidating existing credentials.
//
// The companion defence is the login throttle in lib/auth.js — slow
// hashing stops an offline attack, the throttle stops an online one.
// Neither is sufficient alone.
const PBKDF2_ITERATIONS = 150000;

async function hashPin(pin, { saltHex, iterations = PBKDF2_ITERATIONS } = {}) {
  const subtle = cryptoGlobal && cryptoGlobal.subtle;
  if (!subtle) throw new Error('crypto.subtle unavailable');
  const saltBytes = saltHex
    ? Uint8Array.from((saltHex.match(/.{2}/g) || []).map((b) => parseInt(b, 16)))
    : cryptoGlobal.getRandomValues(new Uint8Array(16));
  const key = await subtle.importKey('raw', utf8(String(pin)), 'PBKDF2', false, ['deriveBits']);
  const bits = await subtle.deriveBits(
    { name: 'PBKDF2', salt: saltBytes, iterations, hash: 'SHA-256' },
    key,
    256
  );
  return {
    salt: toHex(saltBytes),
    iterations,
    hash: toHex(bits),
    encoded: `pbkdf2$sha256$${iterations}$${toHex(saltBytes)}$${toHex(bits)}`,
  };
}

async function verifyPin(pin, encoded) {
  if (!encoded || typeof encoded !== 'string') return false;
  const parts = encoded.split('$');
  // Format: pbkdf2$sha256$<iterations>$<saltHex>$<hashHex>
  if (parts.length !== 5 || parts[0] !== 'pbkdf2' || parts[1] !== 'sha256') return false;
  const iterations = Number(parts[2]);
  if (!Number.isFinite(iterations) || iterations < 1000) return false;
  const candidate = await hashPin(pin, { saltHex: parts[3], iterations });
  return timingSafeEqualStr(candidate.hash, parts[4]);
}

// Constant-time string comparison. crypto.subtle gives us no memcmp, and
// `a === b` on a hash leaks length and first-differing-byte timing —
// irrelevant for a slow PBKDF2 hash in practice, but free to do right.
function timingSafeEqualStr(a, b) {
  if (typeof a !== 'string' || typeof b !== 'string') return false;
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i += 1) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// ---------------------------------------------------------------------
// TIME — WEST AFRICA TIME
// ---------------------------------------------------------------------
// Migration 009 in PharmaRidge fixed a live bug where a sale made between
// 00:00 and 00:59 Lagos time was bucketed under the PREVIOUS calendar day
// in every day-based report, because the reports bucketed on raw UTC.
// That bug is designed out here rather than patched: every "day" in this
// system is a WAT day, computed once, in one place.
//
// Nigeria has observed WAT (UTC+1) with no daylight saving since 1919, so
// a fixed offset is correct and — unlike an IANA lookup — behaves
// identically inside a Cloudflare Worker isolate and on a Node server.
const WAT_OFFSET_MINUTES = 60;

function watNowIso(at = new Date()) {
  const shifted = new Date(at.getTime() + WAT_OFFSET_MINUTES * 60000);
  return shifted.toISOString().slice(0, 19).replace('T', ' ');
}

// 'YYYY-MM-DD' in WAT. THE canonical day bucket for every report, till
// session, attendance day and dashboard figure in the product.
function watDate(at = new Date()) {
  return watNowIso(at).slice(0, 10);
}

function watMonth(at = new Date()) {
  return watNowIso(at).slice(0, 7);
}

// SQLite/D1 store UTC via datetime('now'). Reports must convert, so the
// offset is applied in SQL as well — see watDateExpr() used by the views.
const WAT_SQL_OFFSET = '+1 hour';

function addDays(dateStr, days) {
  const d = new Date(`${String(dateStr).slice(0, 10)}T00:00:00Z`);
  d.setUTCDate(d.getUTCDate() + Number(days || 0));
  return d.toISOString().slice(0, 10);
}

function daysBetween(fromStr, toStr) {
  const a = Date.parse(`${String(fromStr).slice(0, 10)}T00:00:00Z`);
  const b = Date.parse(`${String(toStr).slice(0, 10)}T00:00:00Z`);
  if (!Number.isFinite(a) || !Number.isFinite(b)) return null;
  return Math.round((b - a) / 86400000);
}

function addMonths(dateStr, months) {
  const [y, m, d] = String(dateStr).slice(0, 10).split('-').map(Number);
  if (!y || !m || !d) return null;
  const total = (m - 1) + Number(months || 0);
  const ny = y + Math.floor(total / 12);
  const nm = ((total % 12) + 12) % 12;
  // Clamp to the last day of the target month: 31 Jan + 1 month must be
  // 28/29 Feb, not 3 March. Warranty and instalment due dates both depend
  // on this being sane.
  const lastDay = new Date(Date.UTC(ny, nm + 1, 0)).getUTCDate();
  const nd = Math.min(d, lastDay);
  return `${String(ny).padStart(4, '0')}-${String(nm + 1).padStart(2, '0')}-${String(nd).padStart(2, '0')}`;
}

function isValidIsoDate(s) {
  if (typeof s !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(s)) return false;
  const d = Date.parse(`${s}T00:00:00Z`);
  return Number.isFinite(d);
}

module.exports = {
  newId, refNumber, toHex, utf8, sha256Hex,
  hashPin, verifyPin, timingSafeEqualStr, PBKDF2_ITERATIONS,
  WAT_OFFSET_MINUTES, WAT_SQL_OFFSET, watNowIso, watDate, watMonth,
  addDays, addMonths, daysBetween, isValidIsoDate,
};
'use strict';
