'use strict';
// =====================================================================
// tools/seed.js — BUILD A REALISTIC DEMO DEPLOYMENT
// =====================================================================
// WHAT THIS PRODUCES
//
// A four-business Nigerian trading group on one StockRidge deployment:
//
//   Ridge Electronics Ltd      ELECTRONICS         Ikeja (Lagos) + Onitsha (Anambra)
//   Ridge Furniture Palace     FURNITURE           Lekki (Lagos)
//   Ridge Wholesale Foods      WHOLESALE_RETAIL    Aba (Abia) + Kano (Kano)
//   Ridge Building Supplies    BUILDING_MATERIALS  Ibadan (Oyo)
//
// That shape is deliberate. It exercises every axis the product claims to
// support in one database: multi-business, multi-branch, four vertical
// profiles, intercompany transfers, wholesale price tiers, serial-tracked
// warranty goods, measured sales, instalment plans, layaway, delivery jobs,
// credit sales with a debtor ledger, stocktakes with posted variances, till
// sessions, attendance with geofence flags, and a full set of general-ledger
// books that balance — across roughly 90 days of trading history.
//
// WHY 90 DAYS OF HISTORY RATHER THAN A BLANK DATABASE
//
// A blank database cannot demonstrate anything that matters. "Top products this
// quarter", "debtor ageing", "branch comparison", "margin by category", "which
// instalment plans are in arrears" — every one of those needs a body of past
// transactions, and a prospect who sees empty charts sees no product.
//
// The history is generated by driving the REAL services rather than inserting
// rows directly, so seed data has the same integrity as live data. If the sales
// engine has a bug the seed fails loudly instead of producing plausible-looking
// nonsense — which is how several real bugs in the sale path were found.
//
// WHY EVERY INSERT GOES THROUGH insert()
//
// Hand-written column lists drift from hand-written VALUES lists. Three such
// mismatches existed in the sale path and each one meant that code had never
// run. Building the statement from a single object makes the two impossible to
// separate, and `node tools/sql-audit.js` checks the rest of the codebase.
//
// PIN hashes are generated fresh on every run, so no hash is ever committed and
// the demo PINs must never be used on a real deployment.
// =====================================================================

const path = require('node:path');
const fs = require('node:fs');
const { openDatabase, migrate } = require('../server/lib/db');
const { provisionDeployment, provisionBusiness } = require('../server/services/provisioningService');
const salesService = require('../server/services/salesService');
const glService = require('../server/services/glService');
const { newId, hashPin } = require('../domain/crypto');
const { round2 } = require('../domain/money');
const { addDays, watToday, watNow, watToUtc } = require('../domain/time');
const { buildSchedule } = require('../domain/instalments');
const { classifyAttendance } = require('../domain/geofence');
const { appendChained } = require('../domain/hashChain');
const { getSettings } = require('../domain/planLimits');

// ---------------------------------------------------------------------
// STATEMENT BUILDING
// ---------------------------------------------------------------------
const RAW = Symbol('rawSql');

/** A raw SQL expression, e.g. `sql("datetime('now','-3 days')")`. */
function sql(text, params = []) { return { [RAW]: text, params }; }

/**
 * Build an INSERT from one object.
 *
 * Keys become columns, values become bound parameters — except a `sql()`
 * marker, which is inlined as an expression. The column list and the value list
 * are therefore the same list, and cannot disagree.
 */
function insert(table, obj) {
  const cols = [];
  const vals = [];
  const params = [];
  for (const key of Object.keys(obj)) {
    if (obj[key] === undefined) continue; // omitted means "use the column default"
    cols.push(key);
    const v = obj[key];
    if (v && typeof v === 'object' && v[RAW]) { vals.push(v[RAW]); params.push(...v.params); } else { vals.push('?'); params.push(v); }
  }
  return { sql: `INSERT INTO ${table} (${cols.join(', ')}) VALUES (${vals.join(', ')})`, params };
}

const run = (db, table, obj) => { const q = insert(table, obj); return db.run(q.sql, q.params); };

// ---------------------------------------------------------------------
// TIMESTAMPS
// ---------------------------------------------------------------------
// This schema stores two zones: `sales.sold_at` is WEST AFRICA TIME (it is what
// every trading-day report buckets on) while created_at / updated_at /
// received_at are UTC from datetime('now'). Seeded history has to respect that
// split or the reports it is meant to demonstrate come out an hour off.

/**
 * The trading day this run is anchored to.
 *
 * Set once by main() and read everywhere else. Calling `watToday()` directly at
 * each use meant a run that crossed West Africa midnight part-way through built
 * a database containing two different "todays": a three-sale stub of a day
 * sitting next to a full one, which reads as a hole in the daily-sales chart
 * and looks exactly like a reporting bug. It also made the run irreproducible,
 * because the SET of days generated depended on the second the seed started.
 */
let SEED_TODAY = null;
function seedToday() { return SEED_TODAY || watToday(); }

/** A WAT wall-clock stamp for `seedToday() + dayOffset` at hour:minute. */
function watStamp(dayOffset, hour = 10, minute = 0) {
  return `${addDays(seedToday(), dayOffset)} ${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:00`;
}

/** The UTC instant of that same WAT moment, for created_at-style columns. */
function utcStamp(dayOffset, hour = 10, minute = 0) {
  return watToUtc(watStamp(dayOffset, hour, minute));
}

/**
 * A WAT sale time on `today - dayOffset`, clamped so it is never in the future.
 *
 * Without the clamp, a seed run shortly after midnight WAT generates "today at
 * 15:00" — which has not happened yet — and the sale engine correctly refuses
 * it as SOLD_AT_IN_FUTURE. That is the engine being right and the fixture being
 * wrong, but it silently thins out today's sales and makes the daily chart dip
 * on the most recent day for no reason anyone could diagnose.
 */
function saleStamp(dayOffset, rng) {
  const nowWat = watNow();
  const stamp = watStamp(-dayOffset, between(rng, 9, 19), between(rng, 0, 59));
  // Both are 'YYYY-MM-DD HH:MM:SS' in the same zone, so a string compare is a
  // chronological compare.
  return stamp > nowWat ? watStamp(0, Number(nowWat.slice(11, 13)), Math.max(0, Number(nowWat.slice(14, 16)) - 2)) : stamp;
}

// ---------------------------------------------------------------------
// DEMO CONTENT
// ---------------------------------------------------------------------
const DEMO_PINS = { admin: '90210', owner: '48213', manager: '73914', staff: '26480' };

const GROUP = [
  {
    key: 'electronics', name: 'Ridge Electronics Ltd', profile: 'ELECTRONICS',
    branches: [
      { key: 'ikeja', name: 'Ridge Electronics — Ikeja', code: 'EL-IKEJA', city: 'Ikeja', state: 'Lagos', lga: 'Ikeja', type: 'RETAIL', lat: 6.6018, lng: 3.3515, opening: 250000, manager: { name: 'Emeka Nwosu', username: 'emeka' }, staff: [{ name: 'Blessing Adamu', username: 'blessing' }, { name: 'Tunde Bakare', username: 'tunde' }] },
      { key: 'onitsha', name: 'Ridge Electronics — Onitsha', code: 'EL-ONITSHA', city: 'Onitsha', state: 'Anambra', lga: 'Onitsha North', type: 'WHOLESALE', lat: 6.1522, lng: 6.7833, opening: 180000, manager: { name: 'Ifeoma Eze', username: 'ifeoma' }, staff: [{ name: 'Kelechi Obi', username: 'kelechi' }] },
    ],
  },
  {
    key: 'furniture', name: 'Ridge Furniture Palace', profile: 'FURNITURE',
    branches: [
      { key: 'lekki', name: 'Ridge Furniture — Lekki Showroom', code: 'FU-LEKKI', city: 'Lagos', state: 'Lagos', lga: 'Eti-Osa', type: 'SHOWROOM', lat: 6.4281, lng: 3.5817, opening: 120000, manager: { name: 'Aisha Bello', username: 'aisha' }, staff: [{ name: 'Segun Olaiya', username: 'segun' }, { name: 'Ngozi Umeh', username: 'ngozi' }] },
    ],
  },
  {
    key: 'wholesale', name: 'Ridge Wholesale Foods', profile: 'WHOLESALE_RETAIL',
    branches: [
      { key: 'aba', name: 'Ridge Wholesale — Aba', code: 'WS-ABA', city: 'Aba', state: 'Abia', lga: 'Aba South', type: 'WHOLESALE', lat: 5.1066, lng: 7.367, opening: 400000, manager: { name: 'Uche Anya', username: 'uche' }, staff: [{ name: 'Fatima Yusuf', username: 'fatima' }] },
      { key: 'kano', name: 'Ridge Wholesale — Kano', code: 'WS-KANO', city: 'Kano', state: 'Kano', lga: 'Kano Municipal', type: 'MIXED', lat: 12.0022, lng: 8.592, opening: 300000, manager: { name: 'Musa Ibrahim', username: 'musa' }, staff: [{ name: 'Hauwa Sani', username: 'hauwa' }] },
    ],
  },
  {
    key: 'building', name: 'Ridge Building Supplies', profile: 'BUILDING_MATERIALS',
    branches: [
      { key: 'ibadan', name: 'Ridge Building Supplies — Ibadan', code: 'BM-IBADAN', city: 'Ibadan', state: 'Oyo', lga: 'Ibadan North', type: 'MIXED', lat: 7.3776, lng: 3.947, opening: 350000, manager: { name: 'Yemi Adeyemi', username: 'yemi' }, staff: [{ name: 'Ibrahim Lawal', username: 'ibrahim' }] },
    ],
  },
];

const CUSTOMERS = [
  ['Adaobi Ventures', 'BUSINESS'], ['Musa Abdullahi', 'INDIVIDUAL'], ['Grace Okonkwo Enterprises', 'BUSINESS'],
  ['Bola Adeleke', 'INDIVIDUAL'], ['Chukwuemeka & Sons Ltd', 'BUSINESS'], ['Amina Suleiman', 'INDIVIDUAL'],
  ['Ikeja Plaza Supermarket', 'BUSINESS'], ['Funmi Ajayi', 'INDIVIDUAL'], ['Kaduna Hardware Distributors', 'BUSINESS'],
  ['Obiageli Nnadi', 'INDIVIDUAL'], ['Zenith Interiors Ltd', 'BUSINESS'], ['Sadiq Bello', 'INDIVIDUAL'],
  ['Port Harcourt Appliances', 'BUSINESS'], ['Yetunde Soyinka', 'INDIVIDUAL'], ['Benue Agro Stores', 'BUSINESS'],
  ['Chinedu Opara', 'INDIVIDUAL'],
];

const SUPPLIERS = [
  ['Slot Systems Nigeria Ltd', 'Lagos', 'Lagos', 1], ['Innostar Furniture Works', 'Lagos', 'Lagos', 1],
  ['Nigerian Bottling Company', 'Lagos', 'Lagos', 1], ['Dangote Industries Ltd', 'Lagos', 'Lagos', 1],
  ['Cutix Plc', 'Lagos', 'Ogun', 1], ['Panasonic Nigeria', 'Lagos', 'Lagos', 1],
  ['Alaba International Traders', 'Lagos', 'Lagos', 0], ['Vitafoam Nigeria Plc', 'Lagos', 'Ogun', 1],
  ['Onitsha Main Market Wholesalers', 'Onitsha', 'Anambra', 0], ['Aba Ariaria Merchants', 'Aba', 'Abia', 0],
];

// A stable RNG for helpers defined outside main().
const rngStatic = makeRandom(77123);

const CITIES = [
  ['Lagos', 'Lagos'], ['Abuja', 'FCT'], ['Kano', 'Kano'], ['Port Harcourt', 'Rivers'],
  ['Ibadan', 'Oyo'], ['Onitsha', 'Anambra'], ['Enugu', 'Enugu'], ['Kaduna', 'Kaduna'],
];

const EXPENSES = ['RENT', 'DIESEL_FUEL', 'ELECTRICITY', 'SALARY_WAGES', 'TRANSPORT_LOGISTICS', 'SECURITY', 'CLEANING', 'MARKETING', 'REPAIRS_MAINTENANCE', 'BANK_CHARGES'];

const FAULTS = ['Unit will not power on', 'Screen cracked after two weeks', 'Compressor not cooling', 'Remote control unresponsive', 'Hinges broke on the door', 'Overheating during use', 'Battery drains within an hour'];

// Deterministic pseudo-randomness. A seed that produces different data each run
// cannot be used to reproduce a bug report, which is most of the value a fixture
// database has.
/**
 * mulberry32 — a small, well-distributed 32-bit PRNG.
 *
 * The first version here was a textbook LCG written as
 * `state = (state * 1103515245 + 12345) & 0x7fffffff`. That multiply reaches
 * about 2.4e18, far past the 2^53 limit at which float64 represents every
 * integer exactly, so the product was ROUNDED before the mask was applied. It
 * was still deterministic, but the sequence was degenerate and lumpy, which
 * showed up as sales clustering on some days and vanishing on others.
 * `Math.imul` does the multiply in true 32-bit integer arithmetic.
 */
function makeRandom(seedValue = 20260101) {
  let state = seedValue >>> 0;
  return function random() {
    state = (state + 0x6d2b79f5) >>> 0;
    let z = state;
    z = Math.imul(z ^ (z >>> 15), z | 1);
    z ^= z + Math.imul(z ^ (z >>> 7), z | 61);
    return ((z ^ (z >>> 14)) >>> 0) / 4294967296;
  };
}
const pick = (rng, arr) => arr[Math.floor(rng() * arr.length) % arr.length];
const between = (rng, min, max) => min + Math.floor(rng() * (max - min + 1));
const chance = (rng, pct) => rng() * 100 < pct;

// ---------------------------------------------------------------------
async function main() {
  const args = process.argv.slice(2);
  const argValue = (name, fallback) => {
    const hit = args.find((a) => a.startsWith(`--${name}=`));
    return hit ? hit.split('=')[1] : fallback;
  };
  const dbFile = argValue('db', process.env.STOCKRIDGE_DB || path.join(__dirname, '..', '.data', 'stockridge.db'));
  const days = Number(argValue('days', 90));
  const quiet = args.includes('--quiet');
  const log = (...a) => { if (!quiet) console.log(...a); };

  // A fresh database every run: seeding on top of an existing one would double
  // the catalogue and make the demo figures meaningless.
  for (const suffix of ['', '-wal', '-shm']) {
    const f = dbFile + suffix;
    if (fs.existsSync(f)) fs.rmSync(f);
  }
  fs.mkdirSync(path.dirname(dbFile), { recursive: true });

  log('StockRidge — seeding a demo deployment');
  log('──────────────────────────────────────────────────────────');
  const db = openDatabase({ file: dbFile });
  const migrated = await migrate(db);
  log(`schema       : ${migrated.applied.join(', ') || 'already applied'}`);

  const rng = makeRandom();

  // Capture the trading day ONCE. `watToday()` used to be called inside the day
  // loop, so a seed run that crossed West Africa midnight part-way through
  // produced a database containing two different "todays" — a half-finished day
  // of three sales next to a full one, and a daily-sales chart with a hole in
  // it that looked like a reporting bug. It also made the run irreproducible,
  // because the set of days depended on the second it started.
  SEED_TODAY = watToday();
  const today = SEED_TODAY;

  // ---- business 1 of 4, with its owner, admin and first branches
  const first = GROUP[0];
  const result = await provisionDeployment(db, {
    businessName: first.name,
    profileCode: first.profile,
    ownerName: 'Chidinma Okafor',
    ownerUsername: 'owner',
    ownerPin: DEMO_PINS.owner,
    adminUsername: 'admin',
    adminPin: DEMO_PINS.admin,
    branches: first.branches.map((b) => ({
      name: b.name, code: b.code, city: b.city, state: b.state, lga: b.lga, branch_type: b.type,
      latitude: b.lat, longitude: b.lng, opening_cash: b.opening,
      manager: { name: b.manager.name, username: b.manager.username, pin: DEMO_PINS.manager, job_title: 'Branch Manager' },
      staff: b.staff.map((s) => ({ name: s.name, username: s.username, pin: DEMO_PINS.staff, job_title: 'Sales / Cashier' })),
    })),
  });

  const businessIds = { [first.key]: result.businessId };
  const branchIndex = {};
  first.branches.forEach((b, i) => { branchIndex[b.key] = result.branchIds[i]; });
  log(`business 1/4 : ${first.name} (${first.profile}) — ${result.branchIds.length} branches, ${result.provisioned.products} products`);

  // ---- businesses 2-4
  for (const spec of GROUP.slice(1)) {
    const businessId = newId();
    await run(db, 'businesses', {
      id: businessId, name: spec.name, legal_name: spec.name, profile_code: spec.profile,
      tin: String(between(rng, 10000000, 99999999)), cac_reg_no: `RC${between(rng, 100000, 999999)}`,
      vat_registered: 1, is_active: 1, created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    const business = await db.first('SELECT * FROM businesses WHERE id = ?', [businessId]);
    const prov = await provisionBusiness(db, business, { withCatalogue: true });
    businessIds[spec.key] = businessId;

    const ownerId = await db.scalar("SELECT id FROM users WHERE username = 'owner'");
    for (const b of spec.branches) {
      const branchId = newId();
      await run(db, 'branches', {
        id: branchId, business_id: businessId, name: b.name, code: b.code, branch_type: b.type,
        address: `${between(rng, 1, 120)} ${pick(rng, ['Market Road', 'Ring Road', 'Abakaliki Road', 'Kano Road', 'Iwo Road'])}, ${b.city}`,
        city: b.city, state: b.state, lga: b.lga, phone: `080${between(rng, 10000000, 99999999)}`,
        latitude: b.lat, longitude: b.lng, geofence_radius_meters: 120, attendance_mode: 'GEOLOCATION',
        opening_cash: b.opening, is_active: 1, created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
      });
      branchIndex[b.key] = branchId;

      if (b.opening > 0) {
        await run(db, 'branch_safe_ledger', {
          id: newId(), branch_id: branchId, business_id: businessId, entry_type: 'OPENING',
          amount: round2(b.opening), balance_after: round2(b.opening), reason: 'Opening cash float',
          created_by: ownerId, created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
        });
      }
      if (b.manager) {
        const h = await hashPin(DEMO_PINS.manager);
        await run(db, 'users', {
          id: newId(), business_id: businessId, branch_id: branchId, full_name: b.manager.name,
          username: b.manager.username, pin_hash: h.stored, role: 'MANAGER', job_title: 'Branch Manager',
          phone: `081${between(rng, 10000000, 99999999)}`, is_active: 1,
          created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
        });
      }
      for (const st of b.staff) {
        const h = await hashPin(DEMO_PINS.staff);
        await run(db, 'users', {
          id: newId(), business_id: businessId, branch_id: branchId, full_name: st.name,
          username: st.username, pin_hash: h.stored, role: 'STAFF', job_title: 'Sales / Cashier',
          phone: `070${between(rng, 10000000, 99999999)}`, is_active: 1,
          created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
        });
      }
    }
    log(`business ${GROUP.indexOf(spec) + 1}/4 : ${spec.name} (${spec.profile}) — ${spec.branches.length} branch(es), ${prov.products} products`);
  }

  // ---- suppliers. is_manufacturer matters: goods a supplier manufactured
  // itself are not liable to the 2% supply-of-goods WHT deduction.
  const supplierIds = [];
  for (const [name, city, state, isManufacturer] of SUPPLIERS) {
    const id = newId();
    await run(db, 'suppliers', {
      id, business_id: null, name, contact_person: name.split(' ')[0],
      phone: `080${between(rng, 10000000, 99999999)}`, city, state, country: 'Nigeria',
      tin: String(between(rng, 10000000, 99999999)), cac_reg_no: `RC${between(rng, 100000, 999999)}`,
      is_manufacturer: isManufacturer, bank_name: pick(rng, ['Zenith Bank', 'GTBank', 'First Bank', 'Access Bank', 'UBA']),
      bank_account_no: String(between(rng, 1000000000, 9999999999)), bank_account_name: name,
      credit_limit: round2(between(rng, 500000, 8000000)), payment_terms_days: between(rng, 7, 45),
      rating: between(rng, 3, 5),
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    supplierIds.push(id);
  }

  // ---- customers, spread across the branches
  const customerRows = [];
  const allBranchIds = Object.values(branchIndex);
  for (let i = 0; i < CUSTOMERS.length; i += 1) {
    const [name, type] = CUSTOMERS[i];
    const branchId = allBranchIds[i % allBranchIds.length];
    const businessId = await db.scalar('SELECT business_id FROM branches WHERE id = ?', [branchId]);
    const classes = await db.all('SELECT * FROM customer_classes WHERE business_id = ? AND is_deleted = 0 ORDER BY code', [businessId]);
    const cls = type === 'BUSINESS'
      ? classes.find((c) => c.code === 'WHOLESALE') || classes.find((c) => c.code === 'CORPORATE') || classes[0]
      : classes.find((c) => c.code === 'RETAIL') || classes.find((c) => c.code === 'WALK_IN') || classes[0];
    const [city, state] = pick(rng, CITIES);
    const id = newId();
    const creditLimit = cls && Number(cls.credit_allowed) ? round2(Number(cls.default_credit_limit) || 500000) : 0;
    await run(db, 'customers', {
      id, business_id: businessId, branch_id: branchId, customer_class_id: cls ? cls.id : null,
      customer_type: type, name, company_name: type === 'BUSINESS' ? name : null,
      phone: `08${between(rng, 100000000, 999999999)}`, city, state,
      address: `${between(rng, 1, 90)} ${pick(rng, ['Aba Road', 'Herbert Macaulay Way', 'Kaduna Road', 'Ikorodu Road'])}, ${city}`,
      tin: type === 'BUSINESS' ? String(between(rng, 10000000, 99999999)) : null,
      credit_limit: creditLimit, credit_balance: 0,
      payment_terms_days: cls && Number(cls.credit_allowed) ? Number(cls.payment_terms_days) || 14 : 0,
      is_active: 1, created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    customerRows.push({ id, businessId, branchId, name, type });
  }

  // ---- open a till per branch and receive stock for every product
  const products = await db.all('SELECT * FROM products WHERE is_deleted = 0 ORDER BY sku');
  log(`catalogue    : ${products.length} products across 4 profiles`);

  const tillByBranch = {};
  for (const branchId of allBranchIds) {
    const businessId = await db.scalar('SELECT business_id FROM branches WHERE id = ?', [branchId]);
    const manager = await db.first("SELECT * FROM users WHERE branch_id = ? AND role = 'MANAGER' LIMIT 1", [branchId]);
    if (!manager) continue;
    const opening = Number(await db.scalar('SELECT opening_cash FROM branches WHERE id = ?', [branchId])) || 0;
    const tillId = newId();
    await run(db, 'till_sessions', {
      id: tillId, branch_id: branchId, business_id: businessId, user_id: manager.id,
      device_id: `device-${branchId.slice(0, 8)}`, status: 'OPEN',
      opened_at: utcStamp(-days - 1, 8, 0), opening_cash: round2(opening),
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    tillByBranch[branchId] = { id: tillId, manager, businessId };

    const branchProducts = products.filter((p) => String(p.business_id) === String(businessId));
    for (const p of branchProducts) {
      const units = await db.all('SELECT * FROM product_units WHERE product_id = ? AND is_deleted = 0 ORDER BY quantity_in_base ASC, code ASC', [p.id]);
      const variants = await db.all('SELECT * FROM product_variants WHERE product_id = ? AND is_deleted = 0 ORDER BY name', [p.id]);
      const targets = variants.length ? variants : [null];
      const costPerBase = Number(p.cost_price) || 100;

      for (const variant of targets) {
        // Onitsha buys cheaper than Lekki. That is real, and it is what makes a
        // per-branch margin comparison mean something.
        const branchCost = round2(costPerBase * (0.94 + rng() * 0.12));
        const sellPerBase = (variant && Number(variant.selling_price)) || Number(p.selling_price) || round2(branchCost * 1.3);
        const receivedDaysAgo = between(rng, 1, days);
        const qtyBase = Math.max(4, Math.round((Number(p.reorder_level) || 8) * (0.8 + rng() * 2.5)));
        const batchId = newId();
        const batchNo = `B${String(receivedDaysAgo).padStart(3, '0')}-${(p.sku || p.id.slice(0, 4)).replace(/[^A-Za-z0-9]/g, '')}`;

        await run(db, 'stock_batches', {
          id: batchId, branch_id: branchId, business_id: businessId, product_id: p.id,
          variant_id: variant ? variant.id : null, batch_no: batchNo, supplier_id: pick(rng, supplierIds),
          cost_price_per_unit: branchCost, selling_price_per_unit: sellPerBase,
          quantity: qtyBase, quantity_reserved: 0, initial_quantity: qtyBase,
          expiry_date: Number(p.has_expiry) ? addDays(today, between(rng, 60, 720)) : null,
          received_at: utcStamp(-receivedDaysAgo, between(rng, 8, 16), between(rng, 0, 59)),
          received_by: manager.id, status: 'ACTIVE',
          warehouse_zone: pick(rng, ['Aisle A', 'Aisle B', 'Aisle C', 'Warehouse 1', 'Warehouse 2', 'Showroom Floor', 'Yard']),
          created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
        });

        if (Number(p.requires_serial)) {
          // Capped deliberately: a fridge or a phone line could otherwise
          // generate tens of thousands of serial rows for no demo benefit.
          const count = Math.min(qtyBase, 12);
          for (let k = 0; k < count; k += 1) {
            const serialNo = `${(p.sku || 'SN').replace(/[^A-Za-z0-9]/g, '').slice(0, 6).toUpperCase()}${String(receivedDaysAgo).padStart(3, '0')}${String(k + 1).padStart(4, '0')}`;
            const existing = await db.first('SELECT id FROM serial_numbers WHERE serial_no = ?', [serialNo]);
            if (existing) continue;
            const serialId = newId();
            await run(db, 'serial_numbers', {
              id: serialId, product_id: p.id, variant_id: variant ? variant.id : null,
              serial_no: serialNo,
              imei: /PH|LT/.test(p.sku || '') ? String(between(rng, 100000000000000, 999999999999999)) : null,
              batch_id: batchId, branch_id: branchId, status: 'IN_STOCK',
              created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
            });
            // Chained with the SAME field builder the sale path uses, so a
            // verifier recomputing from the stored row gets the same hash.
            const fields = salesService.serialEventFields({
              serial_no: serialNo, event_type: 'RECEIVED', branch_id: branchId, notes: 'Goods received',
            });
            await appendChained(db, {
              table: 'serial_events',
              columns: ['id', 'serial_id', 'serial_no', 'event_type', 'to_status', 'branch_id', 'reference_type', 'reference_id', 'actor_id', 'notes'],
              values: [newId(), serialId, serialNo, 'RECEIVED', 'IN_STOCK', branchId, 'BATCH', batchId, manager.id, 'Goods received'],
              scopeColumn: 'serial_no', scopeValue: serialNo,
              hashFields: fields,
            });
          }
        }
      }
    }
  }

  // ---- VAT on, so the seed demonstrates inclusive extraction end to end.
  //
  // AND THE PLAN SET TO FIT THE DATA THIS FILE CREATES. The demo builds four
  // businesses and six branches; the default settings row allows three and five, so
  // every demo deployment opened with "your plan is nearly full — 6 of 5 branches and
  // 4 of 3 businesses" on the first screen. A demonstration that starts by breaking its
  // own commercial rules teaches the wrong thing about the product, and a client who
  // sees it on day one learns to ignore the banner that is supposed to warn them.
  //
  // The caps are not decorative here — they are what `assertCanCreateBranch` and
  // friends enforce, so the demo has to be INSIDE them for its own flows to work.
  await db.run(`UPDATE client_settings SET vat_enabled = 1, vat_rate_percent = 7.5,
      serial_tracking_enabled = 0,
      max_businesses = 5, max_branches = 10, max_staff = 30 WHERE id = 1`);
  const settings = await getSettings(db);

  // ---- 90 days of trading, driven through the real sale engine
  let salesMade = 0; let salesFailed = 0; let revenue = 0;
  const refusals = new Map();
  const users = await db.all("SELECT * FROM users WHERE is_deleted = 0 AND role IN ('MANAGER','STAFF') ORDER BY username");
  const branches = await db.all('SELECT * FROM branches WHERE is_deleted = 0 ORDER BY code');

  for (let dayOffset = days; dayOffset >= 0; dayOffset -= 1) {
    const day = addDays(today, -dayOffset);
    // Nigerian retail trades hardest on Saturdays and quietest on Sundays.
    // Without that shape the daily-sales chart is flat noise and demonstrates
    // nothing about the reporting.
    const dow = new Date(`${day}T00:00:00Z`).getUTCDay();
    const target = dow === 0 ? between(rng, 1, 3) : dow === 6 ? between(rng, 6, 14) : between(rng, 4, 10);

    for (const branch of branches) {
      const ctx = tillByBranch[branch.id];
      if (!ctx) continue;
      const branchUsers = users.filter((u) => String(u.branch_id) === String(branch.id));
      if (!branchUsers.length) continue;
      const business = await db.first('SELECT * FROM businesses WHERE id = ?', [branch.business_id]);
      const count = Math.max(0, Math.round(target * (0.6 + rng() * 0.9)));

      const managers = branchUsers.filter((u) => u.role === 'MANAGER');
      for (let k = 0; k < count; k += 1) {
        const user = pick(rng, branchUsers);
        const stocked = await db.all(`
          SELECT sb.product_id, sb.variant_id, sb.quantity, sb.quantity_reserved,
                 p.requires_serial, p.base_unit_name,
                 u.code AS unit_code, u.quantity_in_base AS factor
          FROM stock_batches sb
          JOIN products p ON p.id = sb.product_id
          JOIN product_units u ON u.product_id = sb.product_id AND u.is_deleted = 0
               AND u.id = (SELECT uu.id FROM product_units uu WHERE uu.product_id = sb.product_id
                             AND uu.is_deleted = 0
                           ORDER BY uu.is_default_sell DESC, uu.quantity_in_base ASC LIMIT 1)
          WHERE sb.branch_id = ? AND sb.is_deleted = 0 AND sb.status = 'ACTIVE'
            AND sb.quantity - sb.quantity_reserved >= u.quantity_in_base
          -- Ordered by STABLE business keys. Ordering by id or product_id would
          -- sort on freshly generated random hex, which is an arbitrary order
          -- that differs on every run and quietly undoes the reproducibility
          -- this file promises.
          ORDER BY p.sku, sb.batch_no LIMIT 40`, [branch.id]);
        if (!stocked.length) continue;

        // Shuffled with the SEEDED rng, not by SQLite's RANDOM(). The header of
        // this file claims the seed is reproducible so a bug report can be
        // replayed against the same data; `ORDER BY RANDOM()` quietly broke that
        // claim — two runs of the same seed produced 493 and 1,031 sales. A
        // fixture that cannot be reproduced cannot be debugged.
        const pool = [...stocked];
        for (let i = pool.length - 1; i > 0; i -= 1) {
          const j = Math.floor(rng() * (i + 1));
          [pool[i], pool[j]] = [pool[j], pool[i]];
        }

        const lines = [];
        const lineCount = between(rng, 1, Math.min(3, pool.length));
        for (let li = 0; li < lineCount; li += 1) {
          const row = pool[li];
          const free = Number(row.quantity) - Number(row.quantity_reserved);
          if (free <= 0) continue;
          // Sell in the product's OWN default unit. Hard-coding PIECE refused
          // every measured and bagged product — cable is sold by the METRE,
          // cement by the BAG, paint by the LITRE, roofing by the SQUARE_METRE —
          // which was 62% of all refusals in the first seeded run. A fixture
          // that cannot sell two thirds of its own catalogue is not testing the
          // catalogue.
          const line = {
            productId: row.product_id,
            variantId: row.variant_id || undefined,
            quantity: Math.max(1, Math.min(Math.floor(free / (row.factor || 1)) || 1, between(rng, 1, 3))),
            unitCode: row.unit_code || 'PIECE',
          };
          if (Number(row.requires_serial)) {
            const serials = await db.all(`SELECT serial_no FROM serial_numbers
                WHERE product_id = ? AND branch_id = ? AND status = 'IN_STOCK' AND is_deleted = 0
                  AND (? IS NULL OR variant_id = ?) LIMIT ?`,
            [row.product_id, branch.id, row.variant_id || null, row.variant_id || null, line.quantity]);
            if (serials.length < line.quantity) continue;
            line.serialNumbers = serials.map((x) => x.serial_no);
          }
          lines.push(line);
        }
        if (!lines.length) continue;

        const useCustomer = chance(rng, 45);
        const candidate = useCustomer ? pick(rng, customerRows.filter((c) => String(c.branchId) === String(branch.id))) : null;
        const customer = candidate ? await db.first('SELECT * FROM customers WHERE id = ?', [candidate.id]) : null;
        // Credit is attempted only by a user who is ALLOWED to sell on credit.
        // staff_can_sell_on_credit defaults to 0, so a cashier attempting one is
        // correctly refused — but seeding that way produced 44 refusals and a
        // debtor ledger of seven rows, which is too thin to demonstrate ageing,
        // reminder runs or a statement. Route credit through a manager, which is
        // what a real shop does.
        const wantsCredit = Boolean(customer && Number(customer.credit_limit) > 0) && chance(rng, 22);
        const creditUser = wantsCredit && managers.length ? pick(rng, managers) : user;
        const isCredit = wantsCredit && Boolean(managers.length);
        const saleType = isCredit ? 'CREDIT' : (branch.branch_type === 'WHOLESALE' && chance(rng, 50) ? 'WHOLESALE' : 'RETAIL');

        // The sale happened at a plausible hour on that day, in WAT.
        const soldAt = saleStamp(dayOffset, rng);

        // Delivery is decided BEFORE pricing, because the fee is part of the
        // total the customer pays. Deciding it afterwards produced 75 UNDERPAID
        // refusals: the payment was calculated on a total that did not yet
        // include the delivery the same call was about to request.
        const deliveryRequired = chance(rng, 12);
        const deliveryFee = deliveryRequired ? round2(between(rng, 1500, 15000)) : 0;

        // An over-limit sale needs a recorded reason. Supplying one on a slice of
        // attempts exercises the override path instead of only ever hitting
        // CREDIT_OVERRIDE_REASON_REQUIRED, and leaves the owner a realistic list
        // of judgement calls to review — which is the point of requiring the
        // reason rather than blocking the sale.
        //
        // EVERY random draw for this attempt happens here, outside the try.
        // Drawing inside it made the RNG sequence depend on how many sales
        // threw, so one extra refusal shifted every subsequent decision and a
        // tiny difference compounded into hundreds of sales. A reproducible
        // fixture has to consume randomness on a schedule that does not depend
        // on its own failures.
        const creditOverrideReason = isCredit && chance(rng, 30)
          ? pick(rng, ['Long-standing customer, manager approved in person', 'Awaiting a bank transfer confirmed by phone', 'Repeat buyer with a clean payment history'])
          : null;

        try {
          const prepared = await salesService.prepare(db, {
            branch, business, customer, lines, user: creditUser, settings, saleType, tillSessionId: ctx.id,
            deliveryRequired, deliveryFee,
            deliveryAddress: customer ? customer.address || `${customer.city || branch.city} delivery address` : null,
          });
          const total = prepared.totals.total;
          let payments;
          if (isCredit) {
            const deposit = chance(rng, 40) ? round2(total * (0.2 + rng() * 0.3)) : 0;
            payments = [];
            if (deposit > 0) payments.push({ method: 'CASH', amount: deposit, reference: null });
            payments.push({ method: 'CREDIT', amount: round2(total - deposit) });
          } else {
            const method = pick(rng, ['CASH', 'CASH', 'CASH', 'POS_TERMINAL', 'BANK_TRANSFER', 'MOBILE_MONEY']);
            payments = [{
              method, amount: total,
              reference: method === 'CASH' ? null : `REF${between(rng, 100000, 999999)}`,
            }];
          }

          const out = await salesService.complete(db, {
            branch, business, user: creditUser, settings, lines, customer, saleType, payments,
            tillSessionId: ctx.id, soldAt,
            creditOverrideReason,
            deliveryRequired, deliveryFee,
            deliveryAddress: customer ? customer.address || `${customer.city || branch.city} delivery address` : null,
            walkInName: customer ? undefined : pick(rng, ['Walk-in customer', 'Cash customer']),
          });
          salesMade += 1;
          revenue = round2(revenue + out.totals.total);
        } catch (e) {
          salesFailed += 1;
          // A refusal count with no reason is useless: 500 refusals could be one
          // bug or fifty. The first blocking problem is folded into the key so
          // the summary names what actually went wrong.
          const firstProblem = Array.isArray(e.problems) && e.problems.length
            ? e.problems[0].message.replace(/^Line \d+[^:]*: /, '').slice(0, 70)
            : '';
          const key = firstProblem
            ? `${e.code || 'ERROR'} — ${firstProblem}`
            // For a constraint failure the message names the index, which is the
            // only way to tell a receipt-number race from a duplicate serial.
            : `${e.code || 'ERROR'} — ${String(e.message).replace(/\s+/g, ' ').slice(0, 90)}`;
          refusals.set(key, (refusals.get(key) || 0) + 1);
        }
      }
    }
  }
  log(`sales        : ${salesMade} completed over ${days} days, ₦${revenue.toLocaleString('en-NG')} revenue (${salesFailed} refused)`);
  if (salesFailed) {
    const top = [...refusals.entries()].sort((a, b) => b[1] - a[1]).slice(0, 8);
    for (const [k, v] of top) log(`  refused ${String(v).padStart(4)}x  ${k}`);
  }

  // ---- expenses, so the P&L has a cost side
  let expenses = 0;
  for (const branch of branches) {
    const ctx = tillByBranch[branch.id];
    if (!ctx) continue;
    for (let i = 0; i < between(rng, 8, 18); i += 1) {
      const category = pick(rng, EXPENSES);
      const amount = round2(category === 'RENT' ? between(rng, 250000, 1800000)
        : category === 'SALARY_WAGES' ? between(rng, 80000, 450000)
          : between(rng, 3000, 180000));
      const dayOffset = -between(rng, 0, days);
      const expenseId = newId();
      await run(db, 'expenses', {
        id: expenseId, branch_id: branch.id, business_id: branch.business_id, category,
        description: `${category.replace(/_/g, ' ').toLowerCase()} — ${branch.name}`,
        amount, vat_amount: 0, wht_amount: 0, net_amount: amount,
        expense_date: utcStamp(dayOffset, between(rng, 9, 17), between(rng, 0, 59)),
        payment_method: pick(rng, ['CASH', 'BANK_TRANSFER', 'CASH']),
        status: 'APPROVED', paid_from: pick(rng, ['TILL', 'SAFE', 'BANK']),
        created_by: ctx.manager.id,
        created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
      });
      // An expense row with no journal entry is a list of spendings, not
      // accounts: the trial balance would balance while the P&L showed net
      // profit equal to gross profit, silently ignoring every cost the business
      // actually incurred. Posting here is what makes the seeded P&L mean
      // anything — and it exercises the same path the expenses route uses.
      const accountIds = await glService.loadAccountCodes(db, branch.business_id);
      const expenseRow = await db.first('SELECT * FROM expenses WHERE id = ?', [expenseId]);
      for (const st of glService.postExpenseStatements({
        expense: expenseRow, business: { id: branch.business_id }, branch, user: ctx.manager, accountIds,
      })) await db.run(st.sql, st.params);
      expenses += 1;
    }
  }
  log(`expenses     : ${expenses} recorded`);

  // ---- stocktakes with posted variances
  let stocktakes = 0; let varianceUnits = 0;
  for (const branch of branches) {
    const ctx = tillByBranch[branch.id];
    if (!ctx) continue;
    const sessionId = newId();
    await run(db, 'stocktake_sessions', {
      id: sessionId, branch_id: branch.id, business_id: branch.business_id,
      reference: `ST-${branch.code || branch.id.slice(0, 4)}-001`, scope: 'FULL', status: 'COMMITTED',
      opened_by: ctx.manager.id, opened_at: utcStamp(-7, 8, 0),
      committed_by: ctx.manager.id, committed_at: utcStamp(-6, 17, 30),
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });

    const batches = await db.all('SELECT * FROM stock_batches WHERE branch_id = ? AND is_deleted = 0 AND quantity > 0 ORDER BY batch_no LIMIT 25', [branch.id]);
    let varianceValue = 0;
    for (const b of batches) {
      const systemQty = Number(b.quantity);
      // Mostly zero; occasionally a unit or two short (shrinkage), rarely over
      // (a mis-keyed receipt). That is the real distribution.
      const delta = chance(rng, 70) ? 0 : chance(rng, 85) ? -between(rng, 1, 3) : between(rng, 1, 2);
      const counted = Math.max(0, systemQty + delta);
      const variance = counted - systemQty;
      await run(db, 'stocktake_lines', {
        id: newId(), stocktake_id: sessionId, product_id: b.product_id, variant_id: b.variant_id,
        batch_id: b.id, warehouse_zone: b.warehouse_zone, system_qty: systemQty, counted_qty: counted,
        variance, counted_by: ctx.manager.id, counted_at: utcStamp(-6, between(rng, 9, 16), 0),
        created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
      });
      if (variance !== 0) {
        // total_value is SIGNED to match the signed quantity: a write-off is a
        // negative value and a found item a positive one. Storing the absolute
        // value would make a stocktake that found stock look like one that lost
        // it in every variance report.
        const value = round2(variance * Number(b.cost_price_per_unit));
        await run(db, 'stock_adjustments', {
          id: newId(), branch_id: branch.id, business_id: branch.business_id, batch_id: b.id,
          product_id: b.product_id, variant_id: b.variant_id, adjustment_type: 'COUNT_VARIANCE',
          quantity: variance, unit_cost: Number(b.cost_price_per_unit), total_value: value,
          reason: `Stocktake variance at ${b.warehouse_zone || 'the branch'}`, stocktake_id: sessionId,
          created_by: ctx.manager.id, created_at: utcStamp(-6, 17, 0), updated_at: sql("datetime('now')"),
        });
        await db.run("UPDATE stock_batches SET quantity = ?, updated_at = datetime('now') WHERE id = ?", [counted, b.id]);
        varianceValue = round2(varianceValue + Math.abs(value));
        varianceUnits += Math.abs(variance);
      }
    }
    await db.run('UPDATE stocktake_sessions SET total_variance_value = ? WHERE id = ?', [varianceValue, sessionId]);
    stocktakes += 1;
  }
  log(`stocktakes   : ${stocktakes} committed, ${varianceUnits} units of variance posted`);

  const extras = {
    instalments: await seedInstalments(db, rng, days),
    deposits: await seedDeposits(db, rng),
    warranties: await seedWarrantyClaims(db, rng),
    deliveries: await seedDeliveries(db, rng),
    transfers: await seedTransfers(db, branches),
    attendance: await seedAttendance(db, rng, branches),
  };
  log(`plans        : ${extras.instalments} instalment plans, ${extras.deposits} layaway deposits`);
  log(`after-sales  : ${extras.warranties} warranty claims, ${extras.deliveries} delivery jobs`);
  log(`movements    : ${extras.transfers} stock transfers (incl. intercompany)`);
  log(`attendance   : ${extras.attendance} clock-ins (incl. flagged off-site ones)`);

  // ---- sync status, so the sync screen has something to show
  for (const branch of branches) {
    const hoursAgo = between(rng, 0, 40);
    await run(db, 'branch_sync_status', {
      branch_id: branch.id, device_id: `device-${branch.id.slice(0, 8)}`, app_version: '1.0.0',
      last_heartbeat_at: utcStamp(0, 12, 0), last_push_at: utcStamp(0, 11, 0), last_pull_at: utcStamp(0, 10, 0),
      pending_push_count: hoursAgo > 24 ? between(rng, 1, 12) : 0,
      last_sync_error: hoursAgo > 24 ? 'Network unreachable at the branch; queued locally.' : null,
      updated_at: sql("datetime('now')"),
    });
  }

  // ---- final verification
  const counts = {};
  for (const table of ['businesses', 'branches', 'users', 'products', 'product_variants', 'product_units',
    'stock_batches', 'serial_numbers', 'customers', 'sales', 'sale_items', 'sale_payments', 'expenses',
    'instalment_plans', 'deposits', 'warranty_claims', 'delivery_jobs', 'stock_transfers',
    'stocktake_sessions', 'debtor_ledger', 'gl_journal_entries', 'gl_journal_lines', 'staff_attendance']) {
    counts[table] = await db.scalar(`SELECT COUNT(*) FROM ${table}`);
  }
  log('──────────────────────────────────────────────────────────');
  for (const [k, v] of Object.entries(counts)) log(`  ${k.padEnd(22)} ${String(v).padStart(7)}`);

  const tb = await glService.trialBalance(db, {});
  const bs = await glService.balanceSheet(db, {});
  const pl = await glService.profitAndLoss(db, { startDate: addDays(today, -days), endDate: today });
  log('──────────────────────────────────────────────────────────');
  log(`trial balance : DR ₦${tb.totalDebit.toLocaleString('en-NG')} / CR ₦${tb.totalCredit.toLocaleString('en-NG')} — ${tb.balances ? 'BALANCES' : `OUT BY ₦${tb.difference}`}`);
  log(`balance sheet : assets ₦${bs.totalAssets.toLocaleString('en-NG')} vs liabilities+equity ₦${bs.totalLiabilitiesAndEquity.toLocaleString('en-NG')} — ${bs.balances ? 'BALANCES' : `OUT BY ₦${bs.difference}`}`);
  log(`period P&L    : revenue ₦${pl.totalRevenue.toLocaleString('en-NG')}, COGS ₦${pl.totalCogs.toLocaleString('en-NG')}, gross ₦${pl.grossProfit.toLocaleString('en-NG')} (${pl.grossMarginPct}%), net ₦${pl.netProfit.toLocaleString('en-NG')}`);
  if (!tb.balances || !bs.balances) {
    console.error('\nSEED PRODUCED UNBALANCED BOOKS — this is a bug, not a data quirk.');
    db.close();
    process.exit(1);
  }

  log('──────────────────────────────────────────────────────────');
  log('demo sign-in (PINs are hashed fresh on every run):');
  log(`  ADMIN    admin     / ${DEMO_PINS.admin}   vendor seat: plan limits, branding, feature toggles`);
  log(`  OWNER    owner     / ${DEMO_PINS.owner}   all four businesses, all six branches`);
  log(`  MANAGER  emeka     / ${DEMO_PINS.manager}   Ikeja electronics only`);
  log(`  MANAGER  aisha     / ${DEMO_PINS.manager}   Lekki furniture only`);
  log(`  MANAGER  uche      / ${DEMO_PINS.manager}   Aba wholesale only`);
  log(`  STAFF    blessing  / ${DEMO_PINS.staff}   Ikeja counter`);
  log(`  STAFF    segun     / ${DEMO_PINS.staff}   Lekki showroom floor`);
  log('');
  log(`database     : ${dbFile}`);
  log('start it     : npm start');
  db.close();
}

// ---------------------------------------------------------------------
// AFTER-SALES AND FINANCE HISTORY
// ---------------------------------------------------------------------

async function seedInstalments(db, rng, days) {
  // Every credit-capable customer is considered, and roughly half get a plan.
  // The earlier version sampled 14 customers and then took a 60% coin flip, so
  // RNG drift between runs produced anywhere from two plans to ten — and with
  // two there is nothing to demonstrate: no arrears, no ageing, no completed
  // plan to compare against. An instalment book is one of the headline features
  // for the Nigerian market, so it gets a floor rather than a dice roll.
  const customers = await db.all('SELECT * FROM customers WHERE credit_limit > 0 AND is_deleted = 0 ORDER BY name');
  let made = 0;
  let considered = 0;
  for (const c of customers) {
    considered += 1;
    // Alternate deterministically, then let the rng vary the terms.
    if (considered % 2 === 0 && !chance(rng, 30)) continue;
    const branch = await db.first('SELECT * FROM branches WHERE id = ?', [c.branch_id]);
    const manager = await db.first("SELECT * FROM users WHERE branch_id = ? AND role = 'MANAGER' LIMIT 1", [c.branch_id]);
    if (!branch || !manager) continue;

    const principal = round2(between(rng, 150000, 1200000));
    const depositPct = 30;
    const deposit = round2(principal * (depositPct / 100));
    const interestPct = 12;
    const interest = round2(principal * (interestPct / 100));
    const tenure = between(rng, 3, 9);
    const startOffset = -between(rng, 10, days);
    const start = addDays(seedToday(), startOffset);
    const planId = newId();
    const schedule = buildSchedule({
      financedAmount: round2(principal - deposit), instalmentCount: tenure,
      scheduleStart: start, frequency: 'MONTHLY',
    });
    const nextPending = schedule.find((s) => s.status === 'PENDING');

    await run(db, 'instalment_plans', {
      id: planId, plan_no: `IP-${String(made + 1).padStart(4, '0')}`,
      branch_id: branch.id, business_id: branch.business_id, customer_id: c.id,
      principal, interest_percent: interestPct, interest_amount: interest,
      total_payable: round2(principal + interest), deposit_amount: deposit,
      tenure_months: tenure, frequency: 'MONTHLY', schedule_start: start, status: 'ACTIVE',
      // Guarantor capture is standard Nigerian practice for work-and-pay, and is
      // the difference between a recoverable and an unrecoverable book.
      guarantor_name: pick(rng, ['Mr. Okonkwo (brother)', 'Mrs. Bello (employer)', 'Chief Adeyemi', 'Alhaji Sani']),
      guarantor_phone: `080${between(rng, 10000000, 99999999)}`,
      guarantor_id_type: pick(rng, ['NIN', 'DRIVERS_LICENCE', 'VOTERS_CARD']),
      guarantor_id_no: String(between(rng, 10000000000, 99999999999)),
      next_due_date: nextPending ? nextPending.dueDate : schedule[schedule.length - 1].dueDate,
      amount_paid: deposit, outstanding: round2(principal + interest - deposit),
      created_by: manager.id, approved_by: manager.id,
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });

    let paid = deposit;
    for (const item of schedule) {
      const past = new Date(`${item.dueDate}T00:00:00Z`).getTime() < Date.now();
      const isPaid = past && chance(rng, 78);
      const amountPaid = isPaid ? item.amountDue : 0;
      await run(db, 'instalment_schedule', {
        id: newId(), plan_id: planId, seq: item.seq, due_date: item.dueDate,
        amount_due: item.amountDue, amount_paid: amountPaid,
        paid_at: isPaid ? utcStamp(-between(rng, 0, days), 12, 0) : null,
        status: isPaid ? 'PAID' : (past ? 'OVERDUE' : 'PENDING'),
        created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
      });
      if (isPaid) paid = round2(paid + amountPaid);
    }
    const outstanding = round2(principal + interest - paid);
    await db.run('UPDATE instalment_plans SET amount_paid = ?, outstanding = ?, status = ? WHERE id = ?',
      [paid, outstanding, outstanding <= 0.005 ? 'COMPLETED' : 'ACTIVE', planId]);
    made += 1;
  }
  return made;
}

async function seedDeposits(db, rng) {
  const customers = await db.all('SELECT * FROM customers WHERE is_deleted = 0 ORDER BY name LIMIT 20');
  let made = 0;
  for (const c of customers) {
    if (!chance(rng, 35)) continue;
    const batch = await db.first(`SELECT sb.*, p.name AS product_name FROM stock_batches sb
        JOIN products p ON p.id = sb.product_id
        WHERE sb.branch_id = ? AND sb.is_deleted = 0 AND sb.status = 'ACTIVE'
          AND sb.quantity - sb.quantity_reserved >= 1
        ORDER BY sb.batch_no LIMIT 1`, [c.branch_id]);
    if (!batch) continue;
    const staff = await db.first("SELECT * FROM users WHERE branch_id = ? AND role IN ('MANAGER','STAFF') LIMIT 1", [batch.branch_id]);
    if (!staff) continue;

    const price = round2(Number(batch.selling_price_per_unit));
    const deposit = round2(price * 0.4);
    const id = newId();
    await run(db, 'deposits', {
      id, branch_id: batch.branch_id, business_id: batch.business_id, customer_id: c.id,
      product_id: batch.product_id, variant_id: batch.variant_id, batch_id: batch.id,
      deposit_type: 'LAYAWAY', quantity: 1, unit_code: 'PIECE', quantity_in_base: 1,
      unit_price: price, total_price: price, deposit_amount: deposit,
      balance_due: round2(price - deposit),
      expires_at: addDays(seedToday(), between(rng, 10, 60)), status: 'ACTIVE',
      created_by: staff.id,
      notes: 'Layaway — customer paying in instalments before collection',
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    await run(db, 'deposit_payments', {
      id: newId(), deposit_id: id, branch_id: batch.branch_id, amount: deposit, method: 'CASH',
      reference: `LAY-${String(made + 1).padStart(4, '0')}`, received_by: staff.id,
      received_at: utcStamp(-between(rng, 1, 40), 13, 0),
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    // The unit is held against the batch, so the shelf count and the SELLABLE
    // count stay honestly different.
    await db.run("UPDATE stock_batches SET quantity_reserved = quantity_reserved + 1, updated_at = datetime('now') WHERE id = ? AND quantity_reserved < quantity",
      [batch.id]);
    made += 1;
  }
  return made;
}

async function seedWarrantyClaims(db, rng) {
  const serials = await db.all(`SELECT sn.*, p.warranty_months FROM serial_numbers sn
      JOIN products p ON p.id = sn.product_id
      WHERE sn.status = 'SOLD' AND sn.warranty_ends_at IS NOT NULL AND sn.is_deleted = 0
      ORDER BY sn.serial_no LIMIT 40`);
  let made = 0;
  for (const s of serials) {
    if (!chance(rng, 30)) continue;
    const branch = await db.first('SELECT * FROM branches WHERE id = ?', [s.branch_id]);
    const opener = await db.first("SELECT * FROM users WHERE branch_id = ? AND role IN ('MANAGER','STAFF') LIMIT 1", [s.branch_id]);
    if (!branch || !opener) continue;

    // THE OUTCOMES THE SCHEMA DEFINES, NOT THE NOUNS THIS FILE USED TO INVENT.
    //
    // This wrote `REPAIR`, `REPLACE`, `REFUND`, `REJECT` — the vocabulary that existed
    // before migration 0007, which rebuilt the claim table around the six outcomes the
    // resolve route actually accepts: REPAIRED, REPLACED, REFUNDED, REJECTED,
    // SUPPLIER_RETURN, PAID_REPAIR. NOT ONE OF THE FOUR OVERLAPPED, so every seeded
    // claim tripped the new CHECK constraint and **`npm run db:reset` failed outright**
    // — which is the command a new developer runs first, and the one the sample
    // deployment is built from. The migration converted the rows that existed; nothing
    // converted the seeder that writes them.
    //
    // The pairing is the app's own, too: resolving a claim sets its status to CLOSED and
    // records the outcome beside it (see POST /api/warranty-claims/:id/resolve). So a
    // resolved claim here is CLOSED with an outcome, and an open one is somewhere on the
    // way to it — rather than a random status with a random outcome bolted on.
    const OPEN_STATUSES = ['OPEN', 'INSPECTION', 'APPROVED', 'IN_REPAIR'];
    const RESOLUTIONS = ['REPAIRED', 'REPLACED', 'REFUNDED', 'REJECTED', 'SUPPLIER_RETURN', 'PAID_REPAIR'];
    const resolved = chance(rng, 55);
    const status = resolved ? 'CLOSED' : pick(rng, OPEN_STATUSES);
    const resolution = resolved ? pick(rng, RESOLUTIONS) : null;
    const openedOffset = -between(rng, 2, 40);
    await run(db, 'warranty_claims', {
      id: newId(), claim_no: `WC-${String(made + 1).padStart(4, '0')}`,
      business_id: branch.business_id, branch_id: branch.id, sale_id: s.sale_id, serial_id: s.id,
      product_id: s.product_id, variant_id: s.variant_id, customer_id: s.customer_id,
      status, fault_reported: pick(rng, FAULTS),
      fault_found: resolved ? pick(rng, ['Faulty power board', 'Manufacturing defect in panel', 'Compressor failure', 'Confirmed fault, unit replaced']) : null,
      resolution,
      // A rejected claim needs the written explanation the route insists on — without it
      // the demonstration data shows a refusal with no reason, which is the shape the
      // route exists to prevent.
      resolution_notes: resolution === 'REJECTED'
        ? 'Not a manufacturing fault — the unit was connected to an unregulated supply.'
        : null,
      in_warranty: 1, warranty_ends_at: s.warranty_ends_at,
      supplier_id: null, supplier_recovery_amount: 0,
      cost_to_business: resolved ? round2(between(rng, 5000, 120000)) : 0,
      opened_by: opener.id, opened_at: utcStamp(openedOffset, 11, 0),
      resolved_at: resolved ? utcStamp(openedOffset + between(rng, 1, 15), 14, 0) : null,
      closed_at: resolved ? utcStamp(openedOffset + between(rng, 2, 20), 16, 0) : null,
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    made += 1;
  }
  return made;
}

/**
 * Progress the delivery jobs the sale engine already created.
 *
 * It does NOT create jobs. `salesService.complete({ deliveryRequired: true })`
 * writes the job and its items in the same transaction as the sale, which is
 * correct — a delivery sale with no job is a promise nobody is tracking. The
 * first version of this function then inserted a SECOND job for the same sale,
 * so forty sales had two jobs each and the dispatch board showed double the
 * work. Seeding on top of a service that already did the job is how fixtures end
 * up contradicting the code they are meant to demonstrate.
 *
 * So this walks the existing jobs and moves them through their lifecycle, which
 * is also more useful: a board full of PENDING jobs demonstrates nothing about
 * delivery tracking, while a mix of delivered, in-transit and failed ones does.
 */
async function seedDeliveries(db, rng) {
  const jobs = await db.all(`SELECT * FROM delivery_jobs WHERE is_deleted = 0 ORDER BY job_no LIMIT 200`);
  let progressed = 0;
  for (const job of jobs) {
    const status = pick(rng, ['SCHEDULED', 'PICKED', 'IN_TRANSIT', 'DELIVERED', 'DELIVERED', 'DELIVERED', 'FAILED']);
    const delivered = status === 'DELIVERED';
    const dayOffset = -between(rng, 0, 8);
    await db.run(`UPDATE delivery_jobs SET
        status = ?, scheduled_at = ?, fuel_cost = ?, distance_km = ?, attempts = ?,
        delivered_at = ?, delivered_to = ?, notes = ?, updated_at = datetime('now')
      WHERE id = ?`, [
      status,
      utcStamp(dayOffset, between(rng, 9, 16), 0),
      delivered ? round2(between(rng, 2000, 25000)) : 0,
      delivered ? between(rng, 5, 90) : null,
      status === 'FAILED' ? between(rng, 1, 3) : delivered ? 1 : 0,
      delivered ? utcStamp(dayOffset, 15, 0) : null,
      delivered ? pick(rng, ['Customer', 'Security guard', 'Housekeeper', 'Site supervisor']) : null,
      status === 'FAILED' ? 'Customer not reachable at the address; will retry.' : null,
      job.id,
    ]);
    if (delivered) {
      await db.run("UPDATE delivery_job_items SET delivered_qty = quantity, updated_at = datetime('now') WHERE delivery_job_id = ?", [job.id]);
    }
    // A delivered sale is complete; one still travelling is not. This is what
    // makes the "awaiting delivery" report meaningful rather than permanently
    // full.
    const saleStatus = delivered ? 'COMPLETED' : 'PENDING_DELIVERY';
    await db.run("UPDATE sales SET status = ?, updated_at = datetime('now') WHERE id = ? AND status <> 'VOIDED'", [saleStatus, job.sale_id]);
    progressed += 1;
  }
  return progressed;
}

/**
 * An intra-business transfer and an INTERCOMPANY one.
 *
 * Moving stock from the electronics business to the furniture business is not a
 * relocation, it is a sale between two legal entities: it has to post a
 * debtor/creditor pair at transfer price, or the two businesses' margins
 * silently cross-subsidise each other and neither P&L is true. That matters the
 * moment the owner asks which of the two shops is actually making money.
 */
async function seedTransfers(db, branches) {
  let made = 0;

  const writeTransfer = async ({ from, to, intercompany, reference, dayOffset, note }) => {
    const manager = await db.first("SELECT * FROM users WHERE branch_id = ? AND role = 'MANAGER' ORDER BY username LIMIT 1", [from.id]);
    // After a few thousand sales most batches are thin, so requiring four units
    // made the transfer silently not happen at all. One unit is enough to
    // demonstrate the accounting, and a transfer that quietly vanishes is worse
    // than a small one.
    const batch = await db.first(`SELECT * FROM stock_batches
        WHERE branch_id = ? AND is_deleted = 0 AND status = 'ACTIVE'
          AND quantity - quantity_reserved >= 1
        ORDER BY quantity - quantity_reserved DESC LIMIT 1`, [from.id]);
    if (!manager || !batch) return false;

    const qty = Math.max(1, Math.min(3, Math.floor(Number(batch.quantity))));
    const unitCost = Number(batch.cost_price_per_unit);
    // An intercompany move carries a markup: it is a sale, not a relocation.
    const unitTransferPrice = intercompany ? round2(unitCost * 1.08) : unitCost;
    const transferId = newId();

    await run(db, 'stock_transfers', {
      id: transferId, reference, from_branch_id: from.id, to_branch_id: to.id,
      from_business_id: from.business_id, to_business_id: to.business_id,
      is_intercompany: intercompany ? 1 : 0,
      transfer_price: round2(qty * unitTransferPrice), status: 'RECEIVED',
      initiated_by: manager.id, initiated_at: utcStamp(dayOffset, 9, 0),
      dispatched_at: utcStamp(dayOffset, 11, 0),
      received_by: manager.id, received_at: utcStamp(dayOffset + 1, 10, 0),
      courier_name: pick(rngStatic, ['GIG Logistics', 'Own vehicle — KLY-482XC', 'ABC Haulage']),
      notes: note,
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });

    const itemId = newId();
    await run(db, 'stock_transfer_items', {
      id: itemId, transfer_id: transferId, product_id: batch.product_id, variant_id: batch.variant_id,
      from_batch_id: batch.id, unit_code: 'PIECE', quantity_sent: qty, quantity_sent_base: qty,
      quantity_received: qty, unit_cost: unitCost, unit_transfer_price: unitTransferPrice,
      received_at: utcStamp(dayOffset + 1, 10, 0), received_by: manager.id,
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });

    // Guarded on the SELLABLE quantity, not the shelf quantity. Reserved units
    // belong to a layaway, and taking them here breaks the stock_batches CHECK
    // (quantity_reserved <= quantity) and aborts the whole seed.
    const moved = await db.run(`UPDATE stock_batches SET quantity = quantity - ?, updated_at = datetime('now')
        WHERE id = ? AND quantity - quantity_reserved >= ?`, [qty, batch.id, qty]);
    if (!moved.changes) return false;
    const toBatchId = newId();
    await run(db, 'stock_batches', {
      id: toBatchId, branch_id: to.id, business_id: to.business_id, product_id: batch.product_id,
      variant_id: batch.variant_id, batch_no: reference, cost_price_per_unit: unitTransferPrice,
      selling_price_per_unit: Number(batch.selling_price_per_unit),
      quantity: qty, quantity_reserved: 0, initial_quantity: qty,
      received_at: utcStamp(dayOffset + 1, 10, 0), received_by: manager.id, status: 'ACTIVE',
      warehouse_zone: 'Transferred in', notes: `Received on ${reference}`,
      created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
    });
    await db.run('UPDATE stock_transfer_items SET to_batch_id = ? WHERE id = ?', [toBatchId, itemId]);

    // Post the accounting for the move. Intra-business is an asset relocation
    // between branches; intercompany is a sale between two entities and posts a
    // real receivable and payable on each side.
    const accountIdsFrom = await glService.loadAccountCodes(db, from.business_id);
    const statements = intercompany
      ? glService.postIntercompanyTransferStatements({
        transfer: { id: transferId, reference },
        fromBusiness: { id: from.business_id, name: await db.scalar('SELECT name FROM businesses WHERE id = ?', [from.business_id]) },
        toBusiness: { id: to.business_id, name: await db.scalar('SELECT name FROM businesses WHERE id = ?', [to.business_id]) },
        fromBranch: from, toBranch: to, value: round2(qty * unitTransferPrice), accountIds: accountIdsFrom, user: manager,
      })
      : glService.postTransferStatements({
        transfer: { id: transferId, reference }, business: { id: from.business_id },
        fromBranch: from, toBranch: to, value: round2(qty * unitCost), accountIds: accountIdsFrom, user: manager,
      });
    for (const st of statements) await db.run(st.sql, st.params);
    return true;
  };

  const electronics = branches.filter((b) => b.code && b.code.startsWith('EL-'));
  if (electronics.length >= 2) {
    if (await writeTransfer({
      from: electronics[0], to: electronics[1], intercompany: false, reference: 'TRF-00001', dayOffset: -5,
      note: 'Branch rebalance ahead of the weekend.',
    })) made += 1;
  }

  const el = branches.find((b) => b.code && b.code.startsWith('EL-'));
  const fu = branches.find((b) => b.code && b.code.startsWith('FU-'));
  if (el && fu) {
    if (await writeTransfer({
      from: el, to: fu, intercompany: true, reference: 'TRF-00002', dayOffset: -10,
      note: 'Intercompany: an appliance sold from the furniture showroom. Treated as a sale between two entities so both P&Ls stay true.',
    })) made += 1;
  }
  return made;
}

async function seedAttendance(db, rng, branches) {
  const users = await db.all("SELECT * FROM users WHERE is_deleted = 0 AND role IN ('MANAGER','STAFF') ORDER BY username");
  let made = 0;
  for (const u of users) {
    const branch = branches.find((b) => String(b.id) === String(u.branch_id));
    if (!branch) continue;
    for (let d = 14; d >= 1; d -= 1) {
      const day = addDays(seedToday(), -d);
      const dow = new Date(`${day}T00:00:00Z`).getUTCDay();
      if (dow === 0 && !chance(rng, 30)) continue; // many shops close or run short on Sundays
      if (!chance(rng, 88)) continue;              // absence is normal

      const inHour = between(rng, 7, 9);
      const outHour = between(rng, 18, 20);
      // Most clock-ins are on site. A few are off-site or have no fix at all,
      // which is what makes the flag-review screen worth demonstrating — and
      // the flags are ADVISORY: a cashier who cannot get a GPS fix is not
      // prevented from opening the shop.
      const roll = rng();
      const onSite = roll < 0.82;
      const noLocation = roll > 0.94;
      const lat = branch.latitude == null ? null : (onSite ? branch.latitude + (rng() - 0.5) * 0.0008 : branch.latitude + (rng() - 0.5) * 0.02);
      const lng = branch.longitude == null ? null : (onSite ? branch.longitude + (rng() - 0.5) * 0.0008 : branch.longitude + (rng() - 0.5) * 0.02);
      const cls = classifyAttendance({
        branch: {
          latitude: branch.latitude, longitude: branch.longitude,
          geofence_radius_meters: branch.geofence_radius_meters,
          name: branch.name, attendance_mode: branch.attendance_mode,
        },
        latitude: noLocation ? null : lat, longitude: noLocation ? null : lng,
        deviceId: null, registeredDeviceIds: [],
      });

      await run(db, 'staff_attendance', {
        id: newId(), user_id: u.id, branch_id: branch.id, business_id: branch.business_id,
        clock_in_at: watStamp(-d, inHour, between(rng, 0, 59)),
        clock_out_at: watStamp(-d, outHour, between(rng, 0, 59)),
        clock_in_method: 'GEOLOCATION',
        clock_in_lat: lat, clock_in_lng: lng, clock_in_device_id: `device-${branch.id.slice(0, 8)}`,
        location_status: cls.locationStatus, distance_meters: cls.distanceMeters,
        device_status: cls.deviceStatus, flagged: cls.flagged, flag_reason: cls.flagReason,
        hours_worked: round2(outHour - inHour + (rng() - 0.5)),
        created_at: sql("datetime('now')"), updated_at: sql("datetime('now')"),
      });
      made += 1;
    }
  }
  return made;
}

main().catch((e) => {
  console.error('\nSEED FAILED:', e.message);
  if (e.problems) console.error('problems:', JSON.stringify(e.problems, null, 1));
  console.error(e.stack);
  process.exit(1);
});
